version: "3.8"

services:
  indexer:
    build:
      context: .
      dockerfile: ./docker/indexer/Dockerfile
    command: /start-indexer
    volumes:
      - ./emails:/app/emails
    env_file:
      - .env
      - .indexer.env
    ports:
      # .indexer.env defines this port as PROFILING_PORT
      - 6060:6060
    depends_on:
      - zinc
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: ./docker/indexer/Dockerfile
    command: /start-server
    env_file:
      - .env
      - .server.env
    ports:
      - ${API_PORT}:${API_PORT}
      # .server.env defines this port as PROFILING_PORT
      - 6061:6061
    depends_on:
      - zinc
    restart: unless-stopped

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    volumes:
      - zinc-data:/data
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_ADMIN_PASSWORD}
      - ZINC_SERVER_PORT=${ZINC_PORT}
      - ZINC_DATA_PATH=/data
    ports:
      - ${ZINC_PORT}:${ZINC_PORT}
    restart: unless-stopped

volumes:
  zinc-data: {}
