version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    networks:
      - network
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - api
    restart: unless-stopped

  indexer:
    build:
      context: .
      dockerfile: ./docker/local/indexer/Dockerfile
    command: /start-indexer
    volumes:
      - ./${EMAILS_DIR}:/app/${EMAILS_DIR}
    networks:
      - network
    env_file:
      - .env
    environment:
      - ENABLE_PROFILING=${INDEXER_ENABLE_PROFILING}
    ports:
      - ${INDEXER_PROFILING_PORT}:${INDEXER_PROFILING_PORT}
    depends_on:
      - zinc
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: ./docker/local/indexer/Dockerfile
    command: /start-api
    networks:
      - network
    env_file:
      - .env
    environment:
      - ENABLE_PROFILING=${API_ENABLE_PROFILING}
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_PROFILING_PORT}:${API_PROFILING_PORT}
    depends_on:
      - zinc
    restart: unless-stopped

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    volumes:
      - zinc-data:/data
    networks:
      - network
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_ADMIN_PASSWORD}
      - ZINC_SERVER_PORT=${ZINC_PORT}
      - ZINC_DATA_PATH=/data
      - GIN_MODE=release
    ports:
      - ${ZINC_PORT}:${ZINC_PORT}
    restart: unless-stopped

volumes:
  zinc-data: {}

networks:
  network:
    driver: bridge
