#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

zinc_url="http://${ZINC_HOST}:${ZINC_PORT}/version"

echo "Waiting for Zinc server at ${zinc_url} ..."

until curl --output /dev/null --silent --fail "${zinc_url}"; do
  echo "Zinc server not available, sleeping for ${ZINC_RETRY_INTERVAL} seconds ..."
  sleep "${ZINC_RETRY_INTERVAL}"
done

echo "Zinc server is up and running!"

exec "$@"
